### ISSUE TITLE
Path problem with jsn queries

### ISSUE THREAD

**Issue by joshmyzie2** [quintanar401/kdb-wc#1]
I just tried the examples and noticed that half of them don't seem to be working because the queries are trying to call examples/jsn? rather than just jsn?.   Moving the example html files to the main directory fixes them as a workaround.

Example output (the last two queries fail):

```
q)QUERY:
QUERY: examples/base.html
QUERY: external/document-register-element.js
QUERY: kdb-wc.js
QUERY: examples/jsn?enlist {.h.tx[`jsn]:(.j.j');;1}[]
QUERY: examples/jsn?enlist ([] sym: 50?(5?`5);time:.z.T+til[50]*00:00:10; price: 50?40*50?1.0)
```

**Comment by quintanar401** [comment]
Just curious what is your browser (didn't have this problem in mine)?

Probably this is because I don't add the explicit server name to urls. I'll fix it.

**Comment by joshmyzie2** [comment]
That fixed it; works great now.  I'm using Firefox Nightly to connect to a remote q process, but also tried an ancient version of Firefox with a local q process and saw the same behavior.

BTW, thanks for sharing this!  I had hacked together a crude dashboard with R and Shiny for my kdb processes, but it performed terribly and leaked memory.  I was dreading having to learn some javascript to build a nicer dashboard, but it looks like this will do nicely.
