### ISSUE TITLE
Remove handle from cSubs when websocket connection is closed

### ISSUE THREAD

**Issue by joshmyzie2** [quintanar401/kdb-wc#2]
After a websocket subscription is added to cSubs, it is never removed.  For example, after closing wsflow.html, kdb will start throwing errors because the timer is still trying to send on the old handle.

Something like this should fix it:
`.z.wc:@[`.;`cSubs;_;]`

**Comment by quintanar401** [comment]
Yes, thanks. Didn't test on 3.4.
