### ISSUE TITLE
Null values break tables

### ISSUE THREAD

**Issue by leonbaum** [quintanar401/kdb-wc#3]
Is there an easy way to get the following working?  I would expect the null values to be represented by blank cells in the table.
`<kdb-table>([]x:1 0n 3f)</kdb-table>`

Fixing null values would also allow for empty tables to be displayed (after transforming by `1#0#t` to get the column names in the json).

**Comment by quintanar401** [comment]
Fixed - JS null will be converted to ""

**Comment by leonbaum** [comment]
Thanks!  The null values now work as expected.
However, the change appears also to be blanking zero values, e.g.,
`<kdb-table>([]x:1 0 3f)</kdb-table>`
will have a blank 2nd row rather than displaying `0`.

Is there a way to differentiate between null and zero?

**Comment by quintanar401** [comment]
Yes, I always forget that JS treats many things as false.
null and 0 - fixed. I think it is not possible to get undefined.
