### ISSUE TITLE
Some c3 config options not working

### ISSUE THREAD

**Issue by leonbaum** [quintanar401/kdb-wc#4]
When providing a full c3 config in the kdb-query, it seems that some options are ignored.

For example, I tried to disable the points from being shown in the first chart.html example, but even after setting `show` to `false`, the points are still being drawn:

```
  <kdb-query k-update-elements='c1'>`point`data!(enlist enlist[`show]!enlist[`false]; enlist[`columns]!enlist (("data1";30;200;100;400;150;250);("data2";50;20;10;40;15;25)))</kdb-query>
  <kdb-chart k-style='width:800px;height:400px;' k-id="c1"></kdb-chart>
```

Any idea how to debug?  Is it possible to see what javascript is generated?

**Comment by quintanar401** [comment]
You can provide the cfg in JSON format on a html page. And if you want to use Q cfg then just run .j.k on JSON:

q).j.k "{ \"data\": { \"type\": \"spline\"}, \"point\": { \"show\": true }, \"axis\": { \"x\": { \"tick\": { \"rotate\":45 } } } }"
data | (,`type)!,"spline"
point| (,`show)!,1b
axis | (,`x)!+(,`tick)!,,(,`rotate)!,45f

It is clear now where the problem is - you have an extra enlist before show dict, also false should be 0b. "false" is actually true in Javascript.

**Comment by leonbaum** [comment]
Thanks!

**Comment by leonbaum** [comment]
What about functions?  Can they used when specifying a full Q config?  I don't think something like `{ format: d3.format(".2f") }` could be converted to json.  I also tried using `merge-config`, but it doesn't seem to work when using a full Q config, only when passing a Q table as the data.

**Comment by quintanar401** [comment]
You can't pass functions via JSON. The only way is to define the cfg as
some JS variable and refer to it by name:

.cfg.someCfg = { a: function() {} }

later

k-config=".cfg.someCfg"

merge cfg works by merging your cfg that comes from srv into the provided
cfg.

2016-08-18 13:31 GMT+03:00 leonbaum notifications@github.com:

**Comment by leonbaum** [comment]
Thanks.  I had tried using merge-config, but the following example isn't applying `KDB.jscfg`:

```
  <script>KDB.jscfg = { data: { type: 'spline'}, point: { show: false }, axis: { x: { tick: { rotate:45 } } } }</script>
  <kdb-query k-update-elements='c1'>enlist[`data]!enlist enlist[`columns]!enlist[(`ask,30?1f;`bid,30?1f)]</kdb-query>
  <kdb-chart k-style='width:800px;height:400px;' k-id="c1" k-chart-type="merge-config" k-config='KDB.jscfg'></kdb-chart>
```

(The reason I want to pass the full Q config and not just a table is that I will be creating combined scatter and line plots..)

**Comment by quintanar401** [comment]
Is the chartbase last example ok (with srv.q)? I can't see any problem with
it.

You can add debug="true" attr to your query and check what is printed to
the browser console.

2016-08-19 11:58 GMT+03:00 leonbaum notifications@github.com:

**Comment by leonbaum** [comment]
@quintanar401, yes, the last example in chartbase.html works fine.  I can update `KDB.jscfg` and the changes take effect.

But if I modify the `kdb-query` that feeds the chart to be a full Q config (see below), rather than just a Q table with data, then that last example will no longer be affected by `KDB.jscfg`:

```
<kdb-query debug="true" k-update-elements='c6'>enlist[`data]!enlist enlist[`columns]!enlist[(`ask,30?1f;`bid,30?1f)]</kdb-query>
<script>KDB.jscfg = { data: { type: 'spline'}, point: { show: true }, axis: { x: { tick: { rotate:45 } } } }</script>
<kdb-chart debug="true" k-style='width:800px;height:400px;' k-id="c6" k-time-col="time" k-data-cols="ask bid"  k-chart-type="merge-config" k-config='KDB.jscfg'></kdb-chart>
```

I added `debug="true"`, but don't see any errors in the console.

To be clear, I would expect my modified example to still produce a chart using splines (as specified in `KDB.jscfg`), but it instead uses the default lines.

**Comment by quintanar401** [comment]
Yes, there is an issue with C3 cfg. I removed the early return, it should be ok now.

**Comment by leonbaum** [comment]
Awesome.  The charts are working great now!
