### ISSUE TITLE
What version of d3.js and other libraries are you using?

### ISSUE THREAD

**Issue by jzabroski** [quintanar401/kdb-wc#5]
Hi,

This is pretty cool and seems useful to use when experimenting with some stuff using the w32 version of q. However, I would also like to look into helping to contribute, but without knowing library versions, it would be hard to help upgrade and modernize and take advantage of latest tools like d3 4.x

**Comment by quintanar401** [comment]
Hi,

Unfortunately I didn't record the versions but they were the last available as of the previous summer (except JQuery but it has its version in its name). All libs are available in external directory. Feel free to use any library, I don't think it will be hard to migrate to the newer versions.

I don't use d3 btw directly - it is used by c3.js.

**Comment by jzabroski** [comment]
Ideally, we could use more than just c3.js and other d3 libraries. I will compute the sha-1 hash and compare to a javascript cdn version history of each, and use this issue to submit a PR to use a package manager. OK?

**Comment by quintanar401** [comment]
Ok, note though that the intention of the library is to provide easy access to web to people how are unfamiliar with it, so i didn't put this into npm and etc. But it is ok if you want to do it provided it will still be possible to download the lib by itself.

**Comment by quintanar401** [comment]
ah, I've forgot that I have archives of all files. They have versions/dev libs. The versions are:

d3:    version: "3.5.17"
c3: 0.4.11
datatables: 1.10.12
